version: '3.7'
services:
    web_server:
        image: web-service:latest
        build:
            context: .
        container_name: web_service
        working_dir: /var/www/html
        tty: true
        ports:
            - '80:80'
        volumes:
            - '../:/var/www/html'

